- .golangci.yml
- cmd/controller/main.go
- cmd/worker/main.go
- internal/messaging/handler.go
- internal/messaging/nats.go
- internal/messaging/publisher.go
- internal/messaging/publisher_test.go
- internal/messaging/subscriber.go
- internal/messaging/subscriber_test.go
- internal/messaging/types_test.go
This PR adds a subscriber that allows us to receive messages from the NATS worker queue and send them to the right handler.
A handler is any type that uses the Handle interface and can be added to the subscriber when it is created. Each handler is responsible for processing a single kind of message (job).
A follow-up PR will update the Cataloger as well.
> feat: add Subscriber 

- examples/image.yaml
- examples/sbom.yaml
- examples/scanresult.yaml
- examples/vulnerabilityreport.yaml
> chore: update examples

- examples/image.yaml
- examples/sbom.yaml
- examples/vulnerabilityreport.yaml
- internal/storage/store.go
The GuaranteedUpdate function receives a tryUpdate function as a parameter. According to the documentation, the update is retried indefinitely only when an index conflict error occurs. However, we were also retrying indefinitely for other errors, leading to an infinite loop.
This PR fixes that issue.
> fix(storage): tryUpdate should only retry index conflict errors

- internal/storage/store.go
- internal/storage/store_test.go
Return key exists error instead of bubbling up a SQL error.
> fix(storage): return key exists error instead of bubbling up a SQL error

- internal/storage/store_test.go
add tryUpdate non-conflict error test case to GuaranteedUpdate test
Leftover of #37
> test(storage): add tryUpdate non-conflict error test case to GuaranteedUpdate test

- internal/handlers/create_catalog.go
- internal/handlers/create_catalog_test.go
- internal/handlers/generate_sbom.go
- internal/handlers/scan_sbom.go
improve the logic of handlers to cover scenarios where resources already exist
- `CreateCatalogHandler`: skip creation if an `Image` already exists, delete obsolete images.
- `GenerateSBOMHandler`: skip creation if a `SBOM` already exists
- `ScanSBOMHandler`: create or update `VulnerabilityReport`
> fix: improve the logic of handlers to cover scenarios where resources already exist

- internal/controller/image_controller.go
- internal/controller/sbom_controller.go
Adds `spec.imageMetadata.registry` index  to fix the error: "Index with name field:spec.imageMetadata.registry does not exist" when using field selectors.
> fix(controller): add spec.imageMetadata.registry index to SBOM and Image

- cmd/worker/main.go
- internal/handlers/create_catalog.go
- internal/handlers/create_catalog_test.go
- internal/handlers/generate_sbom.go
- internal/handlers/generate_sbom_test.go
- internal/handlers/scan_sbom.go
- internal/handlers/scan_sbom_test.go
Set owner references for the resources created by the worker.
This ensures that Kubernetes automatically cleans up all related resources when a registry is deleted.
> feat(worker): set owner references

- Tiltfile
- cmd/controller/main.go
- cmd/storage/main.go
- cmd/storage/server/start.go
- cmd/worker/main.go
- go.mod
- internal/apiserver/apiserver.go
- internal/handlers/create_catalog.go
- internal/handlers/create_catalog_test.go
- internal/handlers/generate_sbom.go
- internal/handlers/generate_sbom_test.go
- internal/handlers/registry/client.go
- internal/handlers/scan_sbom.go
- internal/handlers/scan_sbom_test.go
- internal/messaging/subscriber.go
- internal/messaging/subscriber_test.go
- internal/storage/image_store.go
- internal/storage/sbom_store.go
- internal/storage/store.go
- internal/storage/store_test.go
- internal/storage/vulnerabilityreport_store.go
Change logger from `zap` to `slog`.
Note that we are still using `slog` through `logr` in the controller since this is needed by `controller-runtime`.
Fixes: #33
> chore: switch to slog

- Makefile
- helm/templates/_helpers.tpl
- helm/templates/controller/leader_election_role.yaml
- helm/templates/controller/leader_election_rolebinding.yaml
- helm/templates/controller/metrics_auth_role.yaml
- helm/templates/controller/metrics_auth_rolebinding.yaml
- helm/templates/controller/metrics_reader_role.yaml
- helm/templates/controller/role.yaml
- helm/templates/controller/rolebinding.yaml
- helm/templates/controller/service.yaml
- helm/templates/controller/serviceaccount.yaml
- helm/templates/controller/statefulset.yaml
- helm/templates/storage/apiservice.yaml
- helm/templates/storage/auth_delegator_rolebinding.yaml
- helm/templates/storage/auth_reader_rolebinding.yaml
- helm/templates/storage/deployment.yaml
- helm/templates/storage/role.yaml
- helm/templates/storage/rolebinding.yaml
- helm/templates/storage/service.yaml
- helm/templates/storage/serviceaccount.yaml
- helm/templates/worker/deployment.yaml
- helm/templates/worker/role.yaml
- helm/templates/worker/rolebinding.yaml
- helm/templates/worker/serviceaccount.yaml
Resolve an issue in the Helm chart where the labels helper incorrectly set the `app.kubernetes.io/component` label to `worker` for all components.
This issue also caused the storage service to target the controller's pods.
> fix: helm chart labels

- internal/storage/store.go
- internal/storage/store_test.go
Resolve the issue with GuaranteedUpdate saving an empty object instead of the updated data.
Update test to be more strict.
> fix(storage): resolve GuaranteedUpdate saving an empty object instead of the updated one

- internal/storage/store.go
When using resources exposed by the `storage` component with `kube-rs` watch we realized that the client expected a `resourceVersion` set for the list objects.
This PR adds a `resourceVersion` to the list.
Note that this is a quick fix. We will need to work on the pagination in the future and implement a proper `resourceVersion; see: https://github.com/rancher-sandbox/sbombastic/issues/52
> fix(storage): add resourceVersion to list

- internal/handlers/generate_sbom.go
- internal/handlers/scan_sbom.go
Add the SQL driver required by the RPM and Java databases. Use ECR repositories for generating SBOMs, as Trivy treats SBOM generation as a scanning process and attempts to download the vulnerability databases.
> fix(worker): trivy db repositories

- .github/dependabot.yml
Ensure certain kubernetes dependencies are bumped by the same PR, otherwise induvidual PRs are going to fail
> ci: group k8s dependency bumps

- .github/dependabot.yml
Add the missing `k8s.io/apiserver` and reorder it like go.mod.
> chore: fix kubernetes dependabot group

- .github/workflows/ci.yml
- .golangci.yml
- Remove the args in ci.yaml (it override the timeout in .golangci.yml)
- add concurrency in .golangci.yml to improve performance. ([github host runner doc ](https://docs.github.com/en/actions/using-github-hosted-runners/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)shows ubuntu-latest, ci env use 4 core, so I set to 4)
> ci: fix golang ci timeout

- .github/workflows/ci.yml
- https://github.com/rancher-sandbox/sbombastic/pull/114 require the ci env toolchain to be 1.24.1
- https://github.com/golangci/golangci-lint/issues/5225 mentioned from golangci 1.64, support go 1.24, so I upgrade to latest, 1.64.8 (https://github.com/golangci/golangci-lint/issues/5225)
> ci: Bump go-version from 1.23 to 1.24.1

- internal/handlers/registry/client.go
When the scanner finds an OCI image, it should not panic because the platform is not set.
I think the `nil` handling is required, but we should also avoid to look into the details of something like an OCI artifact, given they are out of scope for SBOMbastic.
I'll create a dedicated issue to keep track of that.
> fix: do not panic when image platform is not set

- internal/handlers/create_catalog.go
- internal/handlers/create_catalog_test.go
Fix https://github.com/rancher-sandbox/sbombastic/issues/121
Inside of the development environment, with tilt up, create the following registry definition:
```yaml
apiVersion: sbombastic.rancher.io/v1alpha1
kind: Registry
metadata:
name: kw-controller
namespace: default
spec:
uri: ghcr.io
repositories:
- kubewarden/kubewarden-controller   
```
The scan succeed, Image resources are created.
> fix: add continue to avoid blocking the image generate.

- .github/workflows/ci.yml
- Makefile
> **Superseding** https://github.com/rancher-sandbox/sbombastic/pull/159
Things are broken everywhere, both on `main` and on [this branch](https://github.com/rancher-sandbox/sbombastic/pull/159).
Going by steps...
The name of the coverage file (`test.txt`) is not matching any of the known patterns of codecov. Hence there's nothing to upload. Looking at the known patterns, a good one can be `cover.out)
This can be seen by looking at a run like [this one](https://github.com/rancher-sandbox/sbombastic/actions/runs/14832670041/job/41637102649).
The correct name of the GHA **organization** secret holding the codecov token is `CODECOV_TOKEN`. See the following screenshot:
However, when the proper combination of code coverage file + token name is used, the token is not reported as valid. …
> ci: fix codecov report upload

- .github/workflows/ci.yml
- .golangci.yml
- Makefile
- api/storage/v1alpha1/register.go
- api/v1alpha1/registry_types.go
- cmd/controller/main.go
- cmd/storage/server/start.go
- cmd/worker/main.go
- internal/apiserver/apiserver.go
- internal/controller/image_controller.go
- internal/controller/registry_controller.go
- internal/controller/registry_controller_test.go
- internal/controller/sbom_controller.go
- internal/handlers/create_catalog.go
- internal/handlers/create_catalog_test.go
- internal/handlers/generate_sbom.go
- internal/handlers/generate_sbom_test.go
- internal/handlers/registry/client.go
- internal/handlers/scan_sbom.go
- internal/handlers/scan_sbom_test.go
- internal/messaging/publisher.go
- internal/messaging/publisher_test.go
- internal/messaging/subscriber.go
- internal/messaging/subscriber_test.go
- internal/storage/image_store.go
- internal/storage/sbom_store.go
- internal/storage/store.go
- internal/storage/store_test.go
- internal/storage/vulnerabilityreport_store.go
Update to v2 of golangci:
- Change how the linter is installed and started by Makefile
- Update GitHub Action
- Update to latest version of golangci-lint golden configuration
- Address linter warnings
Supersedes https://github.com/rancher-sandbox/sbombastic/pull/147
> chore: update to golangci v2

- helm/templates/_helpers.tpl
- helm/templates/storage/pvc.yaml
- internal/handlers/constants.go
- internal/handlers/create_catalog.go
- internal/handlers/generate_sbom.go
- internal/handlers/scan_sbom.go
- Fix https://github.com/rancher-sandbox/sbombastic/issues/27
- Add the labels in the image / SBOM / VulnerabilityRerport, because these are created by controller
- tilt up 
- create a mock data provided in examples
- ensure the image / SBOM / VulnerabilityRerport has label
> feat: add k8s recommended labels

- .dockerignore
- .github/workflows/e2e.yml
- Makefile
- Tiltfile
- go.mod
- go.sum
- helm/templates/storage/deployment.yaml
- helm/values.yaml
- test/e2e/e2e_suite_test.go
- test/e2e/main_test.go
- Fix https://github.com/rancher-sandbox/sbombastic/issues/32
- Support 
- e2e test in GHA, every 24 hour
- able to run locally
- create cluster, namespace, install by helm with local build controller / worker / storage
- run `make test-e2e`
> feat: add e2e test for sbombastic

- .dockerignore
Tilt wasn't starting since the bin directory contains binaries that Tilt needs to copy into the development Docker image, so it shouldn't be ignored.
> fix(.dockerignore): include bin directory for Tilt development builds

- .golangci.yml
- disable shadow strict mode
- disable golines
- enable ginkgolinter
- enable wrapcheck
> chore: tune golangci-lint configuration

- Tiltfile
This PR updates the worker's  `restart_file` path in the Tiltfile. Tilt is incompatible with volume mounts, and we've moved `/tmp` to an `emptyDir` volume.
> fix(Tiltfile): change worker restart_file location

- .github/workflows/e2e.yml
- .gitignore
- test/e2e/main_test.go
Currently, there is no mechanism to debug e2e test failures.
This PR adds support for exporting cluster logs during e2e test runs. 
When the CI workflow fails, the logs are also uploaded as a GitHub Actions artifact.
> test(e2e): export cluster logs

- .github/workflows/e2e.yml
This is a temporary workaround to address the "no space left on device" error documented in issue #228.
The error occurs when pulling the vulnerability database during e2e test execution.
The free space script is based on https://github.community/t/bigger-github-hosted-runners-disk-space/17267/11
and https://github.com/jlumbroso/free-disk-space/blob/main/action.yml. 
We are not using the action directly because it is not included in Rancher's allowed actions list.
We should consider transitioning to self-hosted or enterprise runners, especially since the situation will likely worsen once multiscanner support is introduced.
Fixes #228
> ci(e2e): workaround, fix no space left on device GH action runner error

- .github/workflows/attestation.yml
- Fix https://github.com/rancher-sandbox/sbombastic/issues/245
- There is an issue when installing through kubewarden, so change it to curl install.
- Install with v0.20.5, verify with shasum
- [RKE2](https://github.com/rancher/rke2/blob/c6c325dd17cbe12eb0a00d31bc8fdb8deeef5f80/.github/actions/install-crane/action.yml#L4)
- [kubewarden](https://github.com/kubewarden/github-actions/blob/6fa3010e6919516b8ba438eec3e6b8c5569a0f76/crane-installer/action.yml#L4
)
on fork mock [release](https://github.com/pohanhuangtw/sbombastic/actions/runs/15624733172).
> fix: install crane througth curl

- helm/README.md
- helm/app-readme.md
- Fix https://github.com/rancher-sandbox/sbombastic/issues/252
- source link should be rancher-sandbox not rancher-box
- heading for readme should be H2
- https://github.com/rancher-sandbox/sbombastic/pull/251
> fix: correct broken source link and adjust heading levels

- .github/workflows/container-build.yaml
- Fix https://github.com/orgs/rancher-sandbox/projects/6/views/1?pane=issue&itemId=115855835&issue=rancher-sandbox%7Csbombastic%7C259
- Use the proper permission to call attestation generation workflow
- To resolve error in [workflows](https://github.com/rancher-sandbox/sbombastic/actions/runs/15734899509)
> fix: add permission when calling attestion generation

- .golangci.yml
- api/v1alpha1/scanjob_types.go
- cmd/controller/main.go
- helm/templates/controller/role.yaml
- helm/templates/crd/sbombastic.rancher.io_scanjobs.yaml
- internal/controller/image_controller_test.go
- internal/controller/registry_controller_test.go
- internal/controller/sbom_controller_test.go
- internal/controller/scanjob_controller.go
- internal/controller/scanjob_controller_test.go
- internal/controller/suite_test.go
Adds the `ScanJob` reconciler.
When a `ScanJob` is created, if the target of the `ScanJob` Registry exists in the same namespace, a `CreateCatalog ' message is sent to the queue. 
Part of: #269
> feat(controller): add ScanJob reconciler

- charts/sbombastic/templates/_helpers.tpl
- charts/sbombastic/templates/controller/deployment.yaml
- charts/sbombastic/templates/storage/deployment.yaml
- charts/sbombastic/templates/worker/deployment.yaml
- charts/sbombastic/tests/controller/deployment_test.yaml
- charts/sbombastic/tests/storage/deployment_test.yaml
- charts/sbombastic/tests/worker/deployment_test.yaml
- charts/sbombastic/values.yaml
- Fix https://github.com/rancher-sandbox/sbombastic/issues/309
- ensure the registry setting from global.cattle.systemDefaultRegistry only
- ensure  the tag use chart appVersion as default if tag in value is empty.
- make helm-unittest
> feat: support rancher global registry setting

- .github/workflows/helm-chart-release.yml
- charts/sbombastic/Chart.yaml
- Bump the chart version for testing the helm chart release pipeline.
> chore: bump helm version and ensure release is latest

- Tiltfile
- tilt-settings.yaml.example
This PR:
- Corrects the Helm repository name for cert-manager in the Tiltfile.
- Introduces a registry setting to support the change introduced in #310, where image values no longer include the registry prefix and must be specified separately.
> fix: Tiltfile 

- charts/sbombastic/Chart.yaml
- updatecli/updatecli.d/helm-chart-update.yaml
- Fix https://github.com/rancher-sandbox/sbombastic/issues/319
- read the pre-release, release version
- update version correctly
> feat: update cli support version pattern

- charts/sbombastic/templates/controller/cert-manager.yaml
- charts/sbombastic/templates/controller/deployment.yaml
- charts/sbombastic/templates/controller/service.yaml
- charts/sbombastic/templates/controller/webhooks.yaml
- cmd/controller/main.go
- internal/webhook/v1alpha1/scanjob_webhook.go
- internal/webhook/v1alpha1/scanjob_webhook_test.go
This PR adds a validating webhook for ScanJob validation with the following rules:
**On creation:**
- Block ScanJobs with names longer than 63 characters (k8s label max length). We use ScanJob names as labels to identify the vulnerability reports they create/update.
- Block creation if another ScanJob for the same registry is already running
**On update:**
- Make the registry field immutable
It also sets up webhook TLS in the controller and creates the validating webhook configuration.
Fixes #268 
Related to #241
> feat: add ScanJob webhook

- Tiltfile
- test/e2e/main_test.go
Bumps to latest cert-manager version in the Tiltfile and e2e tests
> build(deps): bump cert-manager to 1.18.2

- internal/controller/scanjob_controller_test.go
Something went wrong during a rebase, causing the ScanJob controller test to fail to compile. This PR fixes the issue.
> fix(controller): use new message struct in ScanJob controller test

- api/labels.go
- api/v1alpha1/scanjob_types.go
- internal/controller/registry_controller.go
- internal/controller/registry_scan_runner.go
- internal/controller/registry_scan_runner_test.go
- internal/controller/scanjob_controller.go
- internal/controller/scanjob_controller_test.go
- internal/controller/vulnerabilityreport_controller.go
- internal/controller/vulnerabilityreport_controller_test.go
- internal/handlers/create_catalog.go
- internal/handlers/create_catalog_test.go
- internal/handlers/scan_sbom.go
- internal/handlers/scan_sbom_test.go
- internal/webhook/v1alpha1/scanjob_webhook.go
- internal/webhook/v1alpha1/scanjob_webhook_test.go
This PR cleans up constants by switching to prefixes instead of suffixes for type naming and moving them into the right packages where needed. It also updates all `MatchingFields` options to use constants instead of string literals for indexes.
> chore: constants cleanup

- examples/vulnerabilityreport.yaml
Update the example of the VulnerabilityReport that we ship with our code to reflect the new format we just introduced.
JFYI: this is a dump of a VulnerabilityReport created by our e2e tests
> doc: update VulnerabilityReport example

- PROJECT
- Tiltfile
- charts/sbombastic/templates/controller/webhooks.yaml
- cmd/controller/main.go
- internal/webhook/v1alpha1/registry_webhook.go
- internal/webhook/v1alpha1/registry_webhook_test.go
This PR adds the `Registry` validating webhook.
For now, it just validates the `scanInterval` field, which must be `>1m`. 
This PR also fixes #400. When a webhook is set up, the API server decodes the Registry object, which means the duration field gets parsed correctly. Before, without the webhook, this didn’t happen and the value was just stored as-is in etcd. I decided not to add a test for this, since it would need an e2e test that basically checks if the API server decoder itself is working.
> feat: add Registry webhook

- internal/handlers/create_catalog.go
- internal/handlers/scanjob_failure.go
- internal/messaging/subscriber.go
This PR addresses an edge case where the handler updates the status condition faster than the controller, leading to conflicts.
It also corrects a misplaced early return that was triggering infinite job retries.
> fix(handlers): ack messages when an error occurs and fix status update conflict

- .github/workflows/ci.yml
- .github/workflows/e2e.yml
- .github/workflows/update-charts.yml
- .github/workflows/updatecli.yaml
- updatecli/updatecli-compose.release.yaml
- updatecli/updatecli-compose.yaml
- updatecli/updatecli.d/go.yaml
- updatecli/updatecli.release.d/helm-chart-update.yaml
To automate the Golang version update, this pull request introduces the following changes
To reduce the number of Golang version, we need to update after new
Golang version, I configure the GitHub action workflow to use
the version defined in the project go.mod
More information on:
* https://github.com/actions/setup-go?tab=readme-ov-file#getting-go-version-from-the-gomod-file
Add an Updatecli manifest to monitor the Golang version defined in the Dockerfile and the go.mod
Add a new GHA workflow to run Updatecli every hour to check for update.
I used the Updatecli compose file to make it easier in the future to add more automation
Simplify the GHA workflow used for updating helm chart which rely on Updatecli to use an Updatecli compose file
to make it easier in the future to add more update …
> chore: Automate Golang version update

- charts/sbombastic/templates/controller/deployment.yaml
- charts/sbombastic/templates/storage/deployment.yaml
- charts/sbombastic/templates/worker/deployment.yaml
- charts/sbombastic/tests/controller/deployment_test.yaml
- charts/sbombastic/tests/storage/deployment_test.yaml
- charts/sbombastic/tests/worker/deployment_test.yaml
- charts/sbombastic/values.yaml
Allow the user to tune the resources (CPU, memory) that SBOMbastic pods are allowed to use.
Currently the limits of the controller are too low, when a scanjob happens the reconciler can exceed the amount of memory the controller is entitled to use. As a result, the controller is terminated by the OOM killer.
Warning: let's discuss what kind of limits and requests we should put as default values for the different components of the stack.
> feat: allow user to customize resources

- test/e2e/e2e_suite_test.go
Add test assertion to e2e tests: ScanJob cascade deletion when a Registry is deleted
> test(e2e): test ScanJob cascade deletion when a Registry is deleted
